### ISSUE TITLE
Integrate semantic-release automation

### ISSUE THREAD

**Issue by petyosi** [telerik/kendo-common-tasks#3]
https://github.com/semantic-release/semantic-release/

Intro to its features:
https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-automating-releases-with-semantic-release 

Notice that we will need #1 and #2 ready before that.

**Comment by gyoshev** [comment]
This was introduced way back in 3f62c7771059ef1a475fdd1f15a3f937379bbf0d
